name: Build Apptainer Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/apptainer
          sudo apt-get update
          sudo apt-get install -y apptainer
          apptainer version # Verify installation

      - name: Build Apptainer image
        run: apptainer build --fakeroot video-depth.sif Apptainer.def

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-depth-sif
          path: video-depth.sif
