name: Build Apptainer Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Apptainer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            uuid-dev \
            libgpgme-dev \
            squashfs-tools \
            libseccomp-dev \
            wget \
            pkg-config \
            git \
            cryptsetup-bin \
            golang-go

      - name: Build and Install Apptainer from source
        env:
          GO_VERSION: '1.22' # Use a modern Go version
        run: |
          git clone https://github.com/apptainer/apptainer.git
          cd apptainer
          ./mconfig --without-suid
          make -C builddir
          sudo make -C builddir install
          apptainer version # Verify installation

      - name: Build Apptainer image
        run: apptainer build --fakeroot video-depth.sif Apptainer.def

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-depth-sif
          path: video-depth.sif
